### ISSUE TITLE
Automatic scroll in deployment stage

### ISSUE THREAD

**Issue by arbulu89** [SUSE-Enceladus/blue-horizon#115]
I have been running some custom deployments with the project, and I have noticed that during the deployment the execution logs are not being scrolled automatically. This is quite annoying as I need to be scrolling down all the time.

Could we have some option to set the automatic scrolling?

**Comment by jesusbv** [comment]
hI @arbulu89 

The [autoscroll checkbox](https://github.com/SUSE-Enceladus/blue-horizon/pull/80) should be there and checked. What version are you running ?

**Comment by arbulu89** [comment]
Hi @jesusbv ,
I cannot find it.
I'm using the image available in the Azure marketplace to deploy the bluehorizon instance: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/suse.cap-deploy-byos?tab=Overview
How can I know the blue horizion version I'm running? I cannot find in the web

If this feature is done but pending to be release or something like that, we can close the ticket.
