### ISSUE TITLE
Unit tests fail if they are executed with other terraform than 0.12.24

### ISSUE THREAD

**Issue by arbulu89** [SUSE-Enceladus/blue-horizon#124]
Hi all,

I have been facing some issues running the unit tests in my system. I have terraform `0.12.26` installed in my system (it is not the latest one neither) and a couple of UT fail because they expect `0.12.24`. This is quite annoying, as it would force me to have this alternative terraform version just to run the test.

The failing tests are in `features/plan_spec.rb`

**Comment by bear454** [comment]
I accidentally fixed this in another PR. ;-)
