### ISSUE TITLE
[suse-cap-deploy-byos-v20200619-hvm] Inserting wrong region will not propagate error in Plan step

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#125]
1. Insert non-existing region in Variables step
2. Save variables and proceed to Plan
3. Click "Plan"
==> You will see just "Execution failed"

Expected: terraform plan actually produce clear error  "Invalid region" , we should propagate it to UI

**Comment by bear454** [comment]
Must be tested with cap-terraform EKS scripts (public-cloud branch): https://github.com/SUSE/cap-terraform/tree/public-cloud/eks
