### ISSUE TITLE
Error handling better  paramter of customisation.yml file. e.g if some parameter are empty, don't let controller crash on rails

### ISSUE THREAD

**Issue by MalloZup** [SUSE-Enceladus/blue-horizon#153]
Moin guys,

I was trying a bit blue-horizon and I found out that if an user miss for example the variable `CLOUD_FRAMEWORK` (not set via env or json) this will cause an exception on the controller and the Webui.

![image](https://user-images.githubusercontent.com/10886597/96375061-0ce44900-1177-11eb-98ad-292c086ef987.png)

as you can see it tries to compose the filepath with an empty var 

It is caused when acessing `http://127.0.0.1:3000/cluster` view

**Comment by bear454** [comment]
cloud_framework _must_ be set, and we cannot and do not want to set a default.

**Comment by bear454** [comment]
All other customizations are optional.
