### ISSUE TITLE
Error using multiple keywords in description with brackets

### ISSUE THREAD

**Issue by arbulu89** [SUSE-Enceladus/blue-horizon#155]
When multiple (2 in my case) keywords with brackets are used in the description field of a variables, and they keywords use brackets, the regular expression are not correctly working.

Example:
```
"deployment_type": {
      "type": "string",
      "default": "Simple",
      "description": "Select to deploy a simple server or a clustered environment with 2 servers with System replication and HA capabilities<!-- Options=[\"Simple\",\"HA\"] [group:HANA configuration] -->"
    },
```

I took a photo with the phone with the error (I cannot take screenshots as the pop up goes away just in the moment of printing the shot...)

![image](https://user-images.githubusercontent.com/36370954/96465237-02828780-1229-11eb-8eac-186a4b6896d3.png)

**Comment by bear454** [comment]
The regex for options needs to search for non-greedy match.

**Comment by arbulu89** [comment]
Yes, it looks trivial.
@bear454 If you want I could have a look myself.
