### ISSUE TITLE
javascript validation could be improved

### ISSUE THREAD

**Issue by MalloZup** [SUSE-Enceladus/blue-horizon#183]
The current validation works seems to work like stack. We show the "top" error fields first.

We should imho show red the fields and then on the `event` cursor Over the element maybe show the error , so it is not sequential, and the user is more intuitive .

See gif

![foo](https://user-images.githubusercontent.com/10886597/99792799-e7f14600-2b27-11eb-9ff0-3d5d5c6f85d0.gif)

**Comment by stefanotorresi** [comment]
I think we're using native HTML5 form browser validation for simplicity here.
@bear454 correct me if I'm wrong, but the proposal would require a completely new implementation of the client-side validation, which is far from trivial, for a little UX improvement!
Besides, if we were to spend more time on the forms, I would probably argue for implementing proper validation in the backend instead.

**Comment by bear454** [comment]
There is no javascript in the validation; this is pure client-side browser implementation of validation. https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation . Building/implementing a JS validation framework would be a huge undertaking, and still doesn't get us true validation, which has to be done by terraform.
