### ISSUE TITLE
Plan view fails if authentication of Azure SP fails

### ISSUE THREAD

**Issue by arbulu89** [SUSE-Enceladus/blue-horizon#195]
The plan view is failing if the authentication of the SP fails, and it returns a error JSON response.

![image](https://user-images.githubusercontent.com/36370954/104717835-3b4bd300-572a-11eb-9340-57479ed99393.png)

In this case, if this is the error, the app should identify and print an easy message, so the user can know that they need to go back to update any of the authentication variables.

**Comment by bear454** [comment]
Please see https://github.com/SUSE-Enceladus/blue-horizon/pull/141
