### ISSUE TITLE
"aditional data" step needs to be revisited 

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#49]
First of all term "Additional data" hard to apply to data which you entering there . Things like subscription ID , client ID and secret are more like core elements ( at least from my understanding ) . 
So maybe we should just rename "additional data" to more accurate name . Another option would be to group fields there in smaller groups/steps and split it to several steps

**Comment by bear454** [comment]
Grouping is something we want to add, but not for 1st release.

Renaming to something more general is a good idea.
