### ISSUE TITLE
"additional data" - cluster labels have sub-optimal flow

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#52]
Every time you enter new key at "Cluster Label" section it cause info section appear at the top of the page saying that value successfully added , this cause web page to scroll to the top . So if you need to enter few values you will need to scroll back to "Cluster Label" after entering every key

**Comment by bear454** [comment]
The buttons were inadvertently submitting the form; that's been resolved.

As a bonus, you can now use the Enter key to move through multiple submissions... e.g.:
type in key [Enter] -> focusses value
type in value [Enter] -> adds map, focusses new key
