### ISSUE TITLE
"Plan" needs download plan button

### ISSUE THREAD

**Issue by asmorodskyi** [SUSE-Enceladus/blue-horizon#54]
Output of plan is pretty huge , users might want to download it for review

**Comment by bear454** [comment]
Once the plan has been run, the download function works, and the user can download the terraform plan artifact.

**Comment by asmorodskyi** [comment]
> Once the plan has been run, the download function works, and the user can download the terraform plan artifact.

If you speaking about ability to download full archive with **everything** inside than my idea was something different . When I entered to `/plan` and wanted to analyze it very quick I understand that it is not comfortable to do in the browser . Next thing I tried is just select it with Ctrl+A but it does not help because Ctrl+A selecting all text in a page not just content of plan output . At this point I realized that I really missing "Download Plan" functionality. 
Will download full archive -> unpack it -> pickup the plan is better ? yes for sure . But IMO having ability to download just plan output or ability to select only plan is still needed
